version: '3.8'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    user: root
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/:/etc/logstash/conf.d/
  #    - ./cos-api:/tmp/logs
      - "C:/kmss_workspace/cos-api:/tmp/logs "
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
#    links:
#      - "logstash:logstash"
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
    depends_on:
      - logstash
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    user: root
    volumes:
      - ./elk/kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    entrypoint: ["./bin/kibana", "--allow-root"]
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    user: root
    volumes:
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  app:
    image: 'cos-api:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cos-api
    depends_on:
      - db
      - logstash
      - kibana
      - elasticsearch
    ports:
      - '8084:8084'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cos_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
      - SPRING_DATASOURCE_USERNAME=bizlog
      - SPRING_DATASOURCE_PASSWORD=bizlog
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - elk

  db:
    container_name: db
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - elk

#  prometheus:
#    image: prom/prometheus:v2.42.0
#    container_name: prometheus
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    healthcheck:
#      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
#    networks:
#      - elk


  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=db
      - GF_DATABASE_NAME=${MYSQL_DATABASE}
      - GF_DATABASE_USER=${MYSQL_USER}
      - GF_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - db
    networks:
      - elk




# Volumes
volumes:
  db-data:

networks:
  elk:
    driver: bridge
