version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181
  zipkin:
    image: openzipkin/zipkin:2
    environment:
      - STORAGE_TYPE=mem
      # - SCRIBE_ENABLED=false # Uncomment to disable scribe
      # - SELF_TRACING_ENABLED=true # Uncomment to enable self-tracing
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG # Uncomment to enable debug logging
    ports:
      - 9411:9411 # Port used for the Zipkin UI and HTTP Api
    expose:
      - 9411
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=cos_db
      - MYSQL_TCP_PORT=3307
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - 9092
      - 9093
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "bizlog_data:1:1"
  s3:
    image: adobe/s3mock
    ports:
      - "9090:9090"
    expose:
      - 9090