spring:
  application:
    name: rms-api
  r2dbc:
    name: rl_db
    username: root
    password: root
    url: r2dbc:pool:mysql://localhost:3306/rl_db?zeroDateTimeBehavior=convertToNull&useSSL=false&useServerPrepareStatement=true

server:
  port: 9081

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: beans,env,health,info,metrics,mappings

runner:
  num-customers: 10

springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    groups-order: DESC