spring:
  profiles:
    active: dev
  application:
    name: Client Onboarding Service API
  # profiles:
  #  active:${APP_PROFILE:default}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate.statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  flyway:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cos_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    username: ${SPRING_DATASOURCE_USERNAME:bizlog}
#    password: ${SPRING_DATASOURCE_PASSWORD:bizlog}
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: false

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    type: redis
  data:

    redis:
      host: ${redis.url:localhost}
      port: ${redis.port:6379}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cos_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    url: ${mysql.url:jdbc:mysql://test-db.cyexeprmtsrm.ap-south-1.rds.amazonaws.com:3306/cos_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
#    username: ${SPRING_DATASOURCE_USERNAME:bizlog}
#    password: ${SPRING_DATASOURCE_PASSWORD:bizlog}
#    username: "bizlog-test"
#    password: "m$g37}418n7W"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 250 # é feito em miliseconds. O ideal é manter baixo para estorar timeout
      max-lifetime: 600000 #tempo adviso que uso conexão pode ficar aberto (19mins) - security
      maximum-pool-size: 10 #numero até o max 20 conexões com o banco de dados. O ideal é manter baixo
      minimum-idle: 5
      pool-name: master

allowed:
  origin: ${ALLOW_URL:http://localhost:4200}

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:myclientid}
      client-secret: ${CLIENT_SECRET:myclientsecret}

jwt:
  secret: ${JWT_SECRET:aGVsbG9ib3lzaWJvdWdodHNkZmdzZnNoZHNoZmRoc2hzaHNoc2hlbGxvYm95c2lib3VnaHRzZGZnc2ZzaGRzaGZkaHNoc2hzaHNoZWxsb2JveXNpYm91Z2h0c2RmZ3Nmc2hkc2hmZGhzaHNoc2hzaGVsbG9ib3lzaWJvdWdodHNkZmdzZnNoZHNoZmRoc2hzaHNoc2hlbGxvYm95c2lib3VnaHRzZGZnc2ZzaGRzaGZkaHNoc2hzaHNoZWxsb2JveXNpYm91Z2h0c2RmZ3Nmc2hkc2hmZGhzaHNoc2hz}
  duration: ${JWT_DURATION:8640000}

####
## Patment Processing with stripe
# Dummy key
stripe:
  key:
    secret: ${STRIPE_SKEY:sk_test_51LeP5ZSTEbgQpy2wcWh9NByZsgonJqfKVkGxZitaX14DY2QEnkseKIydc9ehbv6p7Gy8yK8Ec2UbAUi6onJSPpCK00QXjAzyhk}

server:
  port: 8084
  compression:
    enabled: false
  undertow:
    threads:
      worker: 64
      io: 4

springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    groups-order: DESC

elasticsearch:
  cluster-name: spring-boot-cluster
  host: localhost
  port: 9300

logging:
  file:
    name: Springboot-Elk.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Istanbul
  logback:
    rollingpolicy:
      file-name-pattern: Springboot-Elk-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: true
      max-file-size: 100KB
      total-size-cap: 1MB
      max-history: 14


  # Enable management endpoints
  management.endpoints.web.exposure.include : "*"
  management.endpoint.health.show-details : always
  management.health.probes.enabled : true