global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cos-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cos-api:8084']
        labels:
          application: Client Onboarding Service API
