apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: host.docker.internal:3307
    user: bizlog
    jsonData:
      database: cos_db
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: bizlog
#  - name: Prometheus
#    type: prometheus
#    access: proxy
#    orgId: 1
#    url: http://prometheus:9090
#    basicAuth: false
#    isDefault: true
#    editable: true

