{
 "title": "Cos-Api",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number Of Client Onboarded till Today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cos_db",
     "rawSql": "SELECT COUNT(id) FROM cos_db.client LIMIT 50 "
    }
   ]
  },
  {
   "title": "Client Onboarded today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_FORMAT(time, '%Y-%m-%d') AS day,\r\n  COUNT(id) AS count_per_day\r\nFROM\r\n  cos_db.client\r\nWHERE\r\n  DATE(time) = CURDATE() -- Include records only for the current date\r\nGROUP BY\r\n  day\r\nLIMIT\r\n  50;"
    }
   ]
  },
  {
   "title": "client onboarded this month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_FORMAT(time, '%Y-%m-%d') AS day,\r\n  COUNT(id) AS count_per_day\r\nFROM\r\n  cos_db.client\r\nWHERE\r\n  YEAR(time) = YEAR(CURDATE()) AND MONTH(time) = MONTH(CURDATE()) -- Include records only for the current month\r\nGROUP BY\r\n  day\r\nLIMIT\r\n  50;"
    }
   ]
  },
  {
   "title": "Number of Client onboarded per month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_FORMAT(time, '%Y-%m') AS month,\r\n  COUNT(id) AS count_per_month\r\nFROM\r\n  cos_db.client\r\nGROUP BY\r\n  month\r\nLIMIT\r\n  50;\r\n"
    }
   ]
  }
 ]
}