name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # For example, us-east-1

#      - name: Run script
#        run: |
#          chmod +x your-script.sh
#          ssh -o StrictHostKeyChecking=no -i /path/to/your/private-key.pem ubuntu@your-ec2-instance-ip "bash -s" < /home/ubuntu/bizlog-app-start.sh
      - name: Run script on EC2 instance via SSM
        run: |
            aws ssm send-command \
              --document-name "AWS-RunShellScript" \
              --targets "Key=instanceids,Values=<Your-Instance-ID>" \
              --parameters commands=["cd /home/ubuntu","./bizlog-app-start.sh"] \
              --output text